# Generated by Django 4.1.7 on 2023-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=False)),
                ('balance', models.FloatField(max_length=20)),
            ],
        ),
    ]
